import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import arrowRight from '../public/assets/shared/desktop/icon-arrow-right.svg'
import heroImage from '../public/assets/home/desktop/image-hero.jpg'
import heroImageTablet from '../public/assets/home/tablet/image-header.jpg'
import zx9Speaker from '../public/assets/home/desktop/image-speaker-zx9.png'
// import earphones_yx1 from '../public/assets/home/desktop/image-earphones-yx1.jpg'
import best_gear from '../public/assets/shared/desktop/image-best-gear.jpg'

import PlusMinus from '../components/elements/PlusMinus'
import RadioBtn from '../components/elements/RadioBtn'
import { useState } from 'react'
import MainNavigation from '../components/mainNavigation/MainNavigation'
import NavList from '../components/mainNavigation/NavList'
import navListDataIndex from '../navListData.json'

export default function Home() {

  const [numvalue, setNumvalue] = useState(1);

  function stepper(e) {
    const change = e.target.innerHTML;

    const max = 5;
    const min = 1;
    
    if (change === " - " && numvalue > min) {
      setNumvalue((prev) => prev-1);
    } else if (change === " + " && numvalue < max) {
      setNumvalue((prev) => prev+1);
    }

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>

        <div className={ styles.hero_section }>
            <Image 
              src={ heroImage }
              className={ styles.desktop_hero_image }
              alt="hero-image-earphones-big"
              quality={100}
              layout="responsive"
            />
            <Image 
              src={ heroImageTablet}
              className={ styles.tablet_hero_image }
              alt="hero-image-earphones"
              quality={100}
              layout="responsive"
            />

          <div className={ styles.hero_text_container }>
              <p className={`overline ${ styles.hero_title_overline }`}>New Product</p>
              <h1>XX99 Mark II Headphones</h1>
              <p className={ styles.hero_paragraph }>Experience natural, lifelike audio and exceptional build quality made for the passionate music enthusiast.</p>
              <button className={`btn-type-1 ${ styles.hero_see_product_button }`}>See product</button>
          </div>
        </div>

        
        <NavList navigationArray={ navListDataIndex } /> 
        

        <div className={ styles.advertisment_zx9_speaker }>
          <div className={ styles.zx9_speaker_image_container}>
            <Image 
                src={ zx9Speaker }
                alt="zx9-speaker"
                quality={100}
                width={756}
                height={918}
                layout="responsive"
                />
          </div>
          <div className={ styles.zx9_speaker_text}>
              <h1>ZX9 Speaker</h1>
              <p className={ styles.zx9_speaker_paragraph }>Upgrade your sound system with the all new ZX9 active speaker. It’s a bookshelf speaker system that offers truly wireless connectivity -- creating new possibilities for more pleasing and practical audio setups.</p>
              <button className={`btn-type-1 ${ styles.zx9_see_product_button }`}>See product</button>
          </div>
        </div>

        <div className={ styles.advertisment_zx7_speaker }>
          <div className={ styles.zx7_speaker_text}>
              <h2>ZX7 Speaker</h2>
              <button className={`btn-type-2 ${ styles.zx7_see_product_button }`}>See product</button>
          </div>
        </div>

        <div className={ styles.earphone_container_grid }>
              <div className={ styles.earphone_background_image_container }></div>
              <div className={ styles.earphone_title_n_button }>
                <h2>YX1 Earphones</h2>
                <button className={`btn-type-2 ${ styles.yx1_see_product_button }`}>See product</button>
              </div>
        </div>

        <div className={ styles.audio_gear_grid }>
              <div className={ styles.audio_gear_text }>
                <h1>Bringing you the <span>best</span> audio gear</h1>
                <p>Located at the heart of New York City, Audiophile is the premier store for high end headphones, 
                    earphones, speakers, and audio accessories. We have a large showroom and luxury demonstration 
                    rooms available for you to browse and experience a wide range of our products. Stop by our store 
                    to meet some of the fantastic people who make Audiophile the best place to buy your portable 
                    audio equipment.</p>
              </div>
              <div className={ styles.best_gear_background_container}>
              </div>
        </div>
        
        <h1>Homepage</h1>
        <h2>Homepage</h2>
        <h3>Homepage</h3>
        <h4>Homepage</h4>
        <h5>Homepage</h5>
        <h6>Homepage</h6>
        <p className='overline'>Homepage</p>
        <p className='sub-title'>Homedsdspage</p>
        <p>Homepage</p>
        <button className='btn-type-1'>See product</button>
        <button className='btn-type-2'>See product</button>
        <button className='btn-type-3'>Shop&nbsp;&nbsp;
          <Image
            src={ arrowRight }
            alt="arrow-right"
          />
        </button>

      <label className="text-btn-label" htmlFor="test">Name</label>
      <input type='text' id="test" placeholder='Insert your name' />



      <RadioBtn innerHTML="e-Money" />

      <PlusMinus stepper={ stepper } defaultValue={ numvalue }/>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
