import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
        
        <h1>Homepage</h1>
        <h2>Homepage</h2>
        <h3>Homepage</h3>
        <h4>Homepage</h4>
        <h5>Homepage</h5>
        <h6>Homepage</h6>
        <p className='overline'>Homepage</p>
        <p className='sub-title'>Homepage</p>
        <p>Homepage</p>
        <button className='btn-type-1'>See product</button>
        <button className='btn-type-2'>See product</button>
        <button className='btn-type-3'>Shop&nbsp;&nbsp;<span className='greater-than'>&gt;</span> </button>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
